version: "3.8"
services:
  ui:
    build: ./frontend
    ports:
      - "8080:8080"
  app:
   build: ./backend
   command: python3 -u app.py
   ports:
     - "5000:5000"
   volumes:
     - ./backend:/app
  db:
   image: mongo:3.6.1
   volumes:
     - "./backend/data:/data/db"
